# Generated by Django 4.2.2 on 2023-06-22 14:12

from django.db import migrations, models
import django.db.models.deletion
import sql_test.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=200)),
                ('marque', models.CharField(default='', max_length=200)),
                ('model', models.CharField(default='', max_length=200)),
                ('buying_price', models.FloatField(default=0, validators=[sql_test.models.is_positive])),
                ('stock', models.IntegerField(default=0, validators=[sql_test.models.is_positive])),
                ('location_price', models.FloatField(default=0, validators=[sql_test.models.is_positive])),
                ('weight', models.FloatField(default=0, validators=[sql_test.models.is_positive])),
                ('minimal_lot', models.IntegerField(default=0, validators=[sql_test.models.is_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asso', models.BooleanField(default=True)),
                ('siret', models.IntegerField(default=0)),
                ('adress', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('user_name', models.CharField(default='', max_length=200)),
                ('user_lastname', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_test.article')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiement', models.BooleanField(default=True)),
                ('a_payer', models.BooleanField(default=False)),
                ('cmd_passe', models.DateTimeField(auto_now_add=True)),
                ('cmd_paye', models.DateTimeField()),
                ('deb_loc', models.DateTimeField()),
                ('end_loc', models.DateTimeField()),
                ('bid_date', models.DateTimeField(blank=True, null=True)),
                ('got_paied', models.DateTimeField(blank=True, null=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_test.client')),
                ('id_commande', models.ManyToManyField(to='sql_test.commande')),
            ],
        ),
    ]
