# Generated by Django 4.2.2 on 2023-08-23 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sql_test.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(default='00000', max_length=5)),
                ('product', models.CharField(default='', max_length=200)),
                ('brand', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('sub_category', models.CharField(default='', max_length=200)),
                ('denomination', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('sell_or_loc', models.BooleanField(default=False)),
                ('is_multiple', models.BooleanField(default=False)),
                ('buying_price', models.FloatField(default=1, validators=[sql_test.models.is_positive])),
                ('stock', models.IntegerField(default=0)),
                ('location_price', models.FloatField(default=1, validators=[sql_test.models.is_positive])),
                ('weight', models.FloatField(default=1, validators=[sql_test.models.is_positive])),
                ('minimal_lot', models.IntegerField(default=1, validators=[sql_test.models.is_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asso', models.BooleanField(default=True)),
                ('siret', models.IntegerField(blank=True, null=True, unique=True)),
                ('adress', models.CharField(default='', max_length=200)),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=200)),
                ('user_lastname', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('phone', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_id', models.CharField(default='', max_length=200)),
                ('is_payed', models.BooleanField(default=False)),
                ('billing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paiment_date', models.DateTimeField(blank=True)),
                ('loc_place', models.CharField(default='', max_length=200)),
                ('start_loc', models.DateTimeField()),
                ('end_loc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_article', to='sql_test.article')),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_article', to='sql_test.article')),
            ],
        ),
        migrations.CreateModel(
            name='CommandLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_test.article')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_test.command')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='articles',
            field=models.ManyToManyField(through='sql_test.CommandLine', to='sql_test.article'),
        ),
        migrations.AddField(
            model_name='command',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sql_test.client'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('email',), name='email'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('siret',), name='siret'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('name',), name='name'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('phone',), name='phone'),
        ),
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='related_components', through='sql_test.Component', to='sql_test.article'),
        ),
    ]
