# Generated by Django 4.2.4 on 2023-08-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='end_loc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='paiment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
