# Generated by Django 4.2.4 on 2023-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0002_alter_command_end_loc_alter_command_paiment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandline',
            name='coeff',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='commandline',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
