# Generated by Django 4.2.4 on 2023-08-31 14:34

from django.db import migrations, models
import sql_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0003_commandline_coeff_commandline_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='deposit',
            field=models.FloatField(default=0, validators=[sql_test.models.is_positive]),
        ),
        migrations.AddField(
            model_name='command',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
