# Generated by Django 4.2.2 on 2023-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0003_alter_vente_cmd_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
