# Generated by Django 4.2.2 on 2023-06-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0004_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='siret',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
