# Generated by Django 4.2.2 on 2023-06-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0005_alter_client_siret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vente',
            old_name='paiement',
            new_name='billing',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='cmd_paye',
            new_name='cmd_payed',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='got_paied',
            new_name='got_payed',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='siret',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('email',), name='email'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('siret',), name='siret'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('name',), name='name'),
        ),
    ]
