# Generated by Django 4.2.2 on 2023-06-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0007_alter_client_email_alter_client_user_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
