# Generated by Django 4.2.2 on 2023-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0010_alter_pack_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='id_pack',
            field=models.ManyToManyField(to='sql_test.pack'),
        ),
    ]
