# Generated by Django 4.2.2 on 2023-08-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0011_vente_id_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='id_commande',
            field=models.ManyToManyField(null=True, to='sql_test.commande'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='id_pack',
            field=models.ManyToManyField(null=True, to='sql_test.pack'),
        ),
    ]
