# Generated by Django 4.2.2 on 2023-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0013_alter_vente_id_commande_alter_vente_id_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='end_loc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
