# Generated by Django 4.2.2 on 2023-08-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0015_alter_vente_id_commande_alter_vente_id_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='prev',
            field=models.BooleanField(default=False),
        ),
    ]
