# Generated by Django 4.2.2 on 2023-08-16 20:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0016_vente_prev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_id', models.CharField(default='', max_length=200)),
                ('is_payed', models.BooleanField(default=False)),
                ('billing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paiment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_loc', models.DateTimeField()),
                ('end_loc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CommandLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KitArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='lot',
            name='article',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='lots',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='id_commande',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='id_pack',
        ),
        migrations.RemoveField(
            model_name='article',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='article',
            name='model',
        ),
        migrations.AddField(
            model_name='article',
            name='is_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
        migrations.AddField(
            model_name='kitarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_test.article'),
        ),
        migrations.AddField(
            model_name='kitarticle',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_test.component'),
        ),
        migrations.AddField(
            model_name='component',
            name='articles',
            field=models.ManyToManyField(related_name='article_components', through='sql_test.KitArticle', to='sql_test.article'),
        ),
        migrations.AddField(
            model_name='component',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_components', to='sql_test.article'),
        ),
        migrations.AddField(
            model_name='commandline',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_test.article'),
        ),
        migrations.AddField(
            model_name='commandline',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_test.command'),
        ),
        migrations.AddField(
            model_name='command',
            name='articles',
            field=models.ManyToManyField(through='sql_test.CommandLine', to='sql_test.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='related_components', through='sql_test.Component', to='sql_test.article'),
        ),
    ]
