# Generated by Django 4.2.2 on 2023-08-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0017_command_commandline_component_kitarticle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='articles',
        ),
        migrations.AddField(
            model_name='component',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_article', to='sql_test.article'),
        ),
        migrations.AddField(
            model_name='component',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='component',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_article', to='sql_test.article'),
        ),
        migrations.DeleteModel(
            name='KitArticle',
        ),
    ]
