# Generated by Django 4.2.2 on 2023-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0018_remove_component_articles_component_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brand',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
