# Generated by Django 4.2.2 on 2023-08-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0019_article_brand_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='loc_place',
            field=models.CharField(default='', max_length=200),
        ),
    ]
