# Generated by Django 4.2.2 on 2023-08-21 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0020_command_loc_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sql_test.client'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('phone',), name='phone'),
        ),
    ]
