# Generated by Django 4.2.2 on 2023-08-21 09:33

from django.db import migrations, models
import sql_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0021_command_client_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='denomination',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sell_or_loc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='buying_price',
            field=models.FloatField(default=1, validators=[sql_test.models.is_positive]),
        ),
        migrations.AlterField(
            model_name='article',
            name='location_price',
            field=models.FloatField(default=1, validators=[sql_test.models.is_positive]),
        ),
        migrations.AlterField(
            model_name='article',
            name='minimal_lot',
            field=models.IntegerField(default=1, validators=[sql_test.models.is_positive]),
        ),
        migrations.AlterField(
            model_name='article',
            name='weight',
            field=models.FloatField(default=1, validators=[sql_test.models.is_positive]),
        ),
        migrations.AlterField(
            model_name='command',
            name='paiment_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
