# Generated by Django 4.2.2 on 2023-06-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='vente_id',
        ),
    ]
