# Generated by Django 4.2.2 on 2023-06-22 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='bid_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 8, 25, 17, 203736, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vente',
            name='got_paied',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 8, 25, 17, 203736, tzinfo=datetime.timezone.utc)),
        ),
    ]
