# Generated by Django 4.2.2 on 2023-06-22 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='id_bid',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='vente',
            name='cmd_passe',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
