# Generated by Django 4.2.2 on 2023-06-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0002_vente_id_bid_alter_vente_cmd_passe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='cmd_paye',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
