# Generated by Django 4.2.2 on 2023-06-22 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0002_alter_vente_bid_date_alter_vente_got_paied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='bid_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vente',
            name='got_paied',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
