# Generated by Django 4.2.2 on 2023-06-20 07:52

from django.db import migrations, models
import sql_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0002_remove_article_nbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mod',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(validators=[sql_test.models.is_positive]),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(validators=[sql_test.models.is_positive]),
        ),
    ]
