# Generated by Django 4.2.2 on 2023-06-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0003_article_mod_alter_article_price_alter_article_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='mod',
            new_name='model',
        ),
    ]
