# Generated by Django 4.2.2 on 2023-06-20 11:31

from django.db import migrations, models
import django.db.models.deletion
import sql_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_test', '0004_rename_mod_article_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(default=0, validators=[sql_test.models.is_positive]),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0, validators=[sql_test.models.is_positive]),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, validators=[sql_test.models.is_positive])),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_test.article')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_test.client')),
            ],
        ),
    ]
